
        <div class="ui segments">
            <div class="ui segment">
                <div class="ui two column stackable grid">
                    <div class="sixteen wide column">
                        <div class="ui segment">
                            <h1>Sobriety</h1>
                            <ul>
                                <li><a href="https://lacoaa.org/find-a-meeting/" target="_blank">LA Meetings</a></li>
                                <li><a href="http://www.aa.org/pages/en_US/read-the-big-book-and-twelve-steps-and-twelve-traditions" target="_blank">Big Book  and 12 &amp; 12</a></li>
                                <li><a href="http://12step.org/" target="_blank">12 step worksheets</a></li>
                                <li><a href="http://www.sfvhi.org/meeting.htm" target="_blank">SFV H &amp; I</a></li>                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
