        <div class="ui segments">
            <div class="ui segment">
                <div class="ui one column stackable grid">
                    <div class="column">
                        <div class="ui segment feed blog">
                            <h3 class="ui center aligned header homepage-h1">LA Weekly</h3>
                            <div id="rss-feed" class="rss-feed">
                                <div class="loading">Loading...</div>
                            </div>
                        </div>    
                    </div>
                </div>
            </div>
        </div>
        <script>
        window.onload = function(){
          loadEntries('http://www.laweekly.com/index.rss','rss-feed')
        }
        </script>