
        <div class="ui segments">
            <div class="ui segment">
                <div class="ui two column stackable grid">
                    <div class="six wide column">
                        <div class="ui segment">
                            <iframe src="https://weather.com/weather/today/l/91605:4:US" width="100%" height="500" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="ten wide column">
                        <div class="ui segment">
                            <iframe src="https://calendar.google.com/calendar/embed?src=chriswillett77%40gmail.com&ctz=America/Los_Angeles" style="border: 0" width="100%" height="500" frameborder="0" scrolling="no"></iframe>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
